######################## Base Configuration ########################

baseURL = "https://www.truefalse.fr/"
theme = "gosaas-hugo"

defaultContentLanguage = "en"

# Enable i18n
enableInlineShortcodes = true
hasCJKLanguage = false


# Configure the multilingual parameters
[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    

  [languages.fr]
    languageName = "Français"
    contentDir = "content/fr"

  
[Menu]
  # Main Menu
  [[menu.Main]]
  identifier = 'home'
  name = "Home"
  url= "/"
  weight = 1

  [[menu.Main]]
  identifier = 'about'
  name = "About"
  url= "/about/"
  weight = 2

  [[menu.Main]]
  identifier = 'team'
  name = "Team"
  url= "/team/"
  weight = 3

  [[menu.Main]]
  identifier = 'service'
  name = "Service"
  url= "/service/"
  weight = 4


  [[menu.Main]]
  identifier = 'pricing'
  name = "Pricing"
  url= "/pricing/"
  weight = 5

  [[menu.Main]]
  identifier = 'contact'
  name = "Contact"
  url= "/contact/"
  weight = 6

[params]
  logo = "/images/logo_truefalse.png"

 # Navigation get start button
 [params.navButton]
   enable = true
   label = "Request Demo"
   link = "/contact/"

######################## Plugin Configuration ########################

[params.plugins]

[[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
  URL = "plugins/slick/slick.css"
[[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

[[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"

######################## Social Links ########################

[[params.social]]
  name = "Github"
  link = "https://www.github.com/CodeTrueFalse"

[[params.social]]
  name = "Linkedin"
  link = "https://www.linkedin.com/company/truefalsefr"

######################## Meta Data ########################

description = "TrueFalse - Innovate your projects with cutting-edge technology solutions. Specialized in AI, data scraping, and cybersecurity."
author = "TrueFalse"
keywords = "TrueFalse, True False, technology, French Tech, AI, scraping, web development, startup, cybersecurity"
robots = "index, follow"
canonicalURL = "https://www.truefalse.fr/"

googleAnalyticsID = "G-GZMDLKS1TV"

######################## Multilanguage Call to Action ########################

[params.cta]
  [params.cta.en]
    enable = true
    title  = "Want to build your projects with us? Let's talk about it!"
    label = "Contact Us"
    link = "/en/contact/"
  [params.cta.fr]
    enable = true
    title  = "Envie de construire vos projets avec nous ? Parlons-en !"
    label = "Contactez-nous"
    link = "/fr/contact/"

######################## Multilanguage Footer ########################

[params.footer]
    bgImage = "images/backgrounds/footer-bg.png"
  [params.footer.fr]
    content = "Conçu et développé par [Hugo Sibony](https://www.hugosibony.com)"

[[params.footer.card]]
  image = "images/paypal.png"
[[params.footer.card]]
  image = "images/visa.png"
